---
name: setup runner
on:
  push:
    tags:
      - 'rel-*'
jobs:
  prelim:
    runs-on: buildah
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: "${{ github.workspace }}/build.sh"
      - uses: actions/upload-artifact@v2
        with:
          name: "test-${{ github.sha }}.tar"
          path: "${{ github.workspace }}/test.tar"
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ github.ref }}"
          release_name: "Release ${{ gihub.ref }}${{ github.sha }}"
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path/to/asset.zip
          asset_name: asset.zip
          asset_content_type: application/zip
      - name: Publish release
        uses: StuYarrow/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}

